version: '3.2'
services:
#Primary API
    building-up-server:
        depends_on:
            - building-up-db
            - building-up-redis
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        logging:
            driver: "json-file"
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app
            - /usr/src/node_modules
    # Database
    building-up-db:
        image: postgres
        ports:
        - 5432:5432
        volumes:
        - pg_data:/var/lib/postgresql/data/pg_data
        env_file: 
            - development.env
        volumes:
          - type: volume
            source: postgresql
            target: /var/lib/postgresql
          - type: volume
            source: postgresql_data
            target: /var/lib/postgresql/data
        expose:
        - 5432
    building-up-redis:
        image: "redis:alpine"
        ports:
        - "6379:6379"
        command: ["redis-server", "--port", "6379"]
        expose: 
        - 6379


volumes:
    postgresql:
    postgresql_data:

          