version: '3.2'
services:
    #Primary API
    building-up-server:
        depends_on:
            - building-up-db
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        logging:
            driver: "json-file"
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app
            - /usr/src/node_modules
        env_file: 
            - .env
    # Database
    building-up-db:
        image: postgres
        ports:
        - 5432:5432
        volumes:
        - pg_data:/var/lib/postgresql/data/pg_data
        env_file: 
            - .env
        volumes:
          - type: volume
            source: postgresql
            target: /var/lib/postgresql
          - type: volume
            source: postgresql_data
            target: /var/lib/postgresql/data
        expose:
        - 5432

volumes:
    postgresql:
    postgresql_data:
