require('dotenv').config();

module.exports = {
  POSTGRES_PROD_DB: process.env.POSTGRES_PROD_DB,
  POSTGRES_PROD_USER: process.env.POSTGRES_PROD_USER,
  POSTGRES_PROD_PASSWORD: process.env.POSTGRES_PROD_PASSWORD,
  POSTGRES_PROD_HOST: process.env.POSTGRES_PROD_HOST,
  POSTGRES_PROD_PORT: process.env.POSTGRES_PROD_PORT,
  POSTGRES_PROD_URI: process.env.POSTGRES_PROD_URI,
  POSTGRES_USER: process.env.POSTGRES_USER,
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
  POSTGRES_DB: process.env.POSTGRES_DB,
  PGDATA: process.env.PGDATA,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
};
